---
# Docker volume setup
- name: check if volume ({{volume}}) exists
  command: docker volume inspect {{volume}}
  register: result
  ignore_errors: yes
  changed_when: no
- name: create volume ({{volume}})
  command: docker volume create {{volume}}
  when: result is failed

# Deployment
- name: stop redis container
  docker_container:
    name: mastodon-redis
    state: absent
  ignore_errors: yes
  register: container_stop
  until: not container_stop.get("failed")
  retries: 5
  delay: 10
- name: start redis container
  docker_container:
    name: mastodon-redis
    image: redis:{{version}}
    pull: yes
    state: started
    restart_policy: unless-stopped
    networks:
      - name: "{{network}}"
        aliases:
          - redis
    volumes:
      - "{{volume}}:/data"
...
