---
# Nginx config and certificates
- name: create host nginx directories
  file:
    state: directory
    path: "{{item}}"
  with_items:
    - "{{nginx_dir}}"
    - "{{nginx_dir}}/conf.d"
- name: install nginx configuration files
  template:
    src: "{{item}}"
    dest: "{{nginx_dir}}/conf.d/"
  with_items:
    - mastodon.conf
  notify: reload nginx
...
