---
# Docker volume setup
- name: check if volume ({{volume}}) exists
  command: docker volume inspect {{volume}}
  register: result
  ignore_errors: yes
  changed_when: no
- name: create volume ({{volume}})
  command: docker volume create {{volume}}
  when: result is failed

# Deployment
- name: stop postgres container
  docker_container:
    name: mastodon-db
    state: absent
  ignore_errors: yes
  register: container_stop
  until: not container_stop.get("failed")
  retries: 5
  delay: 10
- name: start postgres container
  docker_container:
    name: mastodon-db
    image: postgres:{{version}}
    pull: yes
    state: started
    restart_policy: unless-stopped
    networks:
      - name: "{{network}}"
        aliases:
          - db
    env:
      POSTGRES_DB: "{{pg_user}}"
      POSTGRES_USER: "{{pg_user}}"
      POSTGRES_PASSWORD: "{{pg_password}}"
    volumes:
      - "{{volume}}:/var/lib/postgresql/data"
...
